import pandas as pd
import pytest

from tbainvestetl.alpha import api, table
from tbainvestetl.domain_models.io import SQLParams


@pytest.mark.parametrize(
    "scenario",
    [
        {
            # No changes are required.
            "size": "compact",
            "api_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                ]
            ),
            "db_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/14/22",
                        "open": 144.31,
                        "high": 144.52,
                        "low": 138.19,
                        "close": 138.38,
                        "adjusted_close": 138.38,
                        "volume": 88597969,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064508",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.07,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064509",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064510",
                    },
                ]
            ),
            "expected_prices": pd.DataFrame(
                columns=[
                    "symbol",
                    "date",
                    "open",
                    "high",
                    "low",
                    "close",
                    "adjusted_close",
                    "volume",
                    "dividend_amount",
                    "split_coefficient",
                    "lud",
                ]
            ),
            "expected_should_upload": False,
            "expected_clean_db_table": False,
        },
        {
            # One record needs to be added.
            "size": "compact",
            "api_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                ]
            ),
            "db_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/14/22",
                        "open": 144.31,
                        "high": 144.52,
                        "low": 138.19,
                        "close": 138.38,
                        "adjusted_close": 138.38,
                        "volume": 88597969,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064508",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.07,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064509",
                    },
                ]
            ),
            "expected_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                ]
            ),
            "expected_should_upload": True,
            "expected_clean_db_table": False,
        },
        {
            # Multiple records need to be added, including some missing in the past.
            "size": "compact",
            "api_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/14/22",
                        "open": 144.31,
                        "high": 144.52,
                        "low": 138.19,
                        "close": 138.38,
                        "adjusted_close": 138.38,
                        "volume": 88597969,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064501",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/13/22",
                        "open": 134.99,
                        "high": 143.59,
                        "low": 134.37,
                        "close": 142.99,
                        "adjusted_close": 142.99,
                        "volume": 113223975,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064502",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/12/22",
                        "open": 139.13,
                        "high": 140.36,
                        "low": 138.16,
                        "close": 138.34,
                        "adjusted_close": 138.34,
                        "volume": 70433744,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064503",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/11/22",
                        "open": 139.9,
                        "high": 141.35,
                        "low": 138.22,
                        "close": 138.98,
                        "adjusted_close": 138.98,
                        "volume": 77033672,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064504",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/10/22",
                        "open": 140.42,
                        "high": 141.89,
                        "low": 138.5729,
                        "close": 140.42,
                        "adjusted_close": 140.42,
                        "volume": 74899002,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064505",
                    },
                ]
            ),
            "db_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/7/22",
                        "open": 142.54,
                        "high": 143.1,
                        "low": 139.45,
                        "close": 140.09,
                        "adjusted_close": 140.09,
                        "volume": 85925559,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064503",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/10/22",
                        "open": 140.42,
                        "high": 141.89,
                        "low": 138.57,
                        "close": 140.42,
                        "adjusted_close": 140.42,
                        "volume": 74899002,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064504",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/14/22",
                        "open": 144.31,
                        "high": 144.52,
                        "low": 138.19,
                        "close": 138.38,
                        "adjusted_close": 138.38,
                        "volume": 88597969,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064505",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.07,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064506",
                    },
                ]
            ),
            "expected_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/14/22",
                        "open": 144.31,
                        "high": 144.52,
                        "low": 138.19,
                        "close": 138.38,
                        "adjusted_close": 138.38,
                        "volume": 88597969,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064501",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/13/22",
                        "open": 134.99,
                        "high": 143.59,
                        "low": 134.37,
                        "close": 142.99,
                        "adjusted_close": 142.99,
                        "volume": 113223975,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064502",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/12/22",
                        "open": 139.13,
                        "high": 140.36,
                        "low": 138.16,
                        "close": 138.34,
                        "adjusted_close": 138.34,
                        "volume": 70433744,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064503",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/11/22",
                        "open": 139.9,
                        "high": 141.35,
                        "low": 138.22,
                        "close": 138.98,
                        "adjusted_close": 138.98,
                        "volume": 77033672,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064504",
                    },
                ]
            ),
            "expected_should_upload": True,
            "expected_clean_db_table": False,
        },
        {
            # Stock split forces all records to be updated.
            "size": "full",
            "api_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/19/22",
                        "open": 72.745,
                        "high": 73.35,
                        "low": 70.305,
                        "close": 71.875,
                        "adjusted_close": 71.875,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 72.745,
                        "high": 73.35,
                        "low": 70.305,
                        "close": 71.875,
                        "adjusted_close": 71.875,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 2,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 70.5325,
                        "high": 71.45,
                        "low": 70.135,
                        "close": 71.205,
                        "adjusted_close": 71.205,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 2,
                        "lud": "2022-10-18 21:52:48.064501",
                    },
                ]
            ),
            "db_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.07,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064527",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064528",
                    },
                ]
            ),
            "expected_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/19/22",
                        "open": 72.745,
                        "high": 73.35,
                        "low": 70.305,
                        "close": 71.875,
                        "adjusted_close": 71.875,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 72.745,
                        "high": 73.35,
                        "low": 70.305,
                        "close": 71.875,
                        "adjusted_close": 71.875,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 2,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 70.5325,
                        "high": 71.45,
                        "low": 70.135,
                        "close": 71.205,
                        "adjusted_close": 71.205,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 2,
                        "lud": "2022-10-18 21:52:48.064501",
                    },
                ]
            ),
            "expected_should_upload": True,
            "expected_clean_db_table": True,
        },
        {
            # Database has no data for the stock,
            # but since all data was retrieved it can be uploaded as is.
            "size": "full",
            "api_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                ]
            ),
            "db_prices": pd.DataFrame(
                columns=[
                    "symbol",
                    "date",
                    "open",
                    "high",
                    "low",
                    "close",
                    "adjusted_close",
                    "volume",
                    "dividend_amount",
                    "split_coefficient",
                    "lud",
                ]
            ),
            "expected_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                ]
            ),
            "expected_should_upload": True,
            "expected_clean_db_table": True,
        },
        {
            # Same as before, but since size is now compact
            # the full history has to be retrieved first.
            "size": "compact",
            "api_prices": pd.DataFrame(
                [
                    {
                        "symbol": "AAPL",
                        "date": "10/18/22",
                        "open": 145.49,
                        "high": 146.7,
                        "low": 140.61,
                        "close": 143.75,
                        "adjusted_close": 143.75,
                        "volume": 99136610,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064499",
                    },
                    {
                        "symbol": "AAPL",
                        "date": "10/17/22",
                        "open": 141.065,
                        "high": 142.9,
                        "low": 140.27,
                        "close": 142.41,
                        "adjusted_close": 142.41,
                        "volume": 85250939,
                        "dividend_amount": 0,
                        "split_coefficient": 1,
                        "lud": "2022-10-18 21:52:48.064500",
                    },
                ]
            ),
            "db_prices": pd.DataFrame(
                columns=[
                    "symbol",
                    "date",
                    "open",
                    "high",
                    "low",
                    "close",
                    "adjusted_close",
                    "volume",
                    "dividend_amount",
                    "split_coefficient",
                    "lud",
                ]
            ),
            "expected_prices": pd.DataFrame(
                columns=[
                    "symbol",
                    "date",
                    "open",
                    "high",
                    "low",
                    "close",
                    "adjusted_close",
                    "volume",
                    "dividend_amount",
                    "split_coefficient",
                    "lud",
                ]
            ),
            "expected_should_upload": True,
            "expected_clean_db_table": True,
        },
    ],
)
def test_get_api_prices_to_upload(scenario, sql_params: SQLParams):
    alpha_scraper = api.AlphaScraper()
    prices_keys = ["symbol", "date"]
    alpha_prices = table.AlphaTablePrices("prices_alpha", prices_keys, alpha_scraper, sql_params)

    size = scenario["size"]
    api_prices = scenario["api_prices"]
    db_prices = scenario["db_prices"]
    expected_prices = scenario["expected_prices"]
    expected_should_upload = scenario["expected_should_upload"]
    expected_clean_db_table = scenario["expected_clean_db_table"]

    actual_output = alpha_prices.get_api_prices_to_upload(api_prices, db_prices, size)
    actual_should_upload, actual_clean_db_table, actual_api_prices = actual_output
    exp_should_upload = expected_should_upload
    exp_clean_db_table = expected_clean_db_table
    assert actual_should_upload == exp_should_upload
    assert actual_clean_db_table == exp_clean_db_table
    assert isinstance(actual_api_prices, type(expected_prices))
    assert expected_prices.equals(actual_api_prices)
